### ISSUE TITLE
Feature request part 2 :)

### ISSUE THREAD

**Issue by shaun12121** [Hywela/Tab-Postion-Cuztomizer-Modified#5]
Me again :)

So far your recent update (1.2.7) has implemented the functionality of the feature that I had previously requested. Thank you again for that.

This time I would like to request that you add an option for "In activated order" under the drop down menu titled "Closing" for the "URL match input" function.

If for some reason that is not possible, which could possibly be the case since you had omitted it (unless the omission was by error x_x!), then perhaps allow the user to NOT select an option for the "Closing" drop down. Currently if the user leaves that option unset he is presented with an error of "Closing behavior is not selected". By allowing the user to omit this option he can have the default option for "Activate tab after tab closing" be "in activated order" and manually match for other closing behaviors as necessary.

Thank you again for your time and I hope you and your friends and family are safe :)
-Shaun

PS: your patch notes on the chrome store has a spelling error: 

> 1.2.7
>+ Fixed so it **dosent brake** on update.

**Comment by Hywela** [comment]
Hey : ) 

It was indeed omitted by choice, It was omitted for the simple reason that it will require more testing before im sure it works. 

But since then I reworked the code abit so it should work now. Going to test it over the next few days and if its stable il push a update. 

Thanks for the info about the spelling error. 

Thanks for the request and and I hope all is well with your friends and family also:)
//K

**Comment by shaun12121** [comment]
Great!

Thanks again, and take care.
-Shaun
